version: '3'

services:
  db:
    container_name: db
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=2231
    volumes:
      - mysql-storage:/var/lib/mysql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

  app:
    container_name: app
    build:
      context: ./
      target: start
    volumes:
      - ../:/var/www/project
      - ./nginx/php.ini:/usr/local/etc/php/php.ini
    environment:
      WEB_SERVER_HOST: 'nginx'
      DATABASE_URL: 'mysql://root:2231@db:3306/vimeoDB?serverVersion=8.0'
    links:
      - db

  node:
    container_name: node
    build:
      context: ./
      target: node
    volumes:
      - ../:/var/www/project
    links:
      - app

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - '8080:80'
    volumes:
      - ../public:/var/www/project/public
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app

volumes:
  mysql-storage:
